name: Aditya Trade Waves Daily Run

on:
  schedule:
    # సోమవారం నుండి శుక్రవారం వరకు భారత కాలమానం ప్రకారం ఉదయం 08:35 AM కు రన్ అవుతుంది
    # UTC లో 03:05 AM అంటే IST లో 08:35 AM
    - cron: '5 3 * * 1-5'
  workflow_dispatch: # మనం కావాలనుకున్నప్పుడు టెస్ట్ చేసుకోవడానికి

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Market Bot
        run: |
          python main.py
