name: Aditya Trade Waves Live Market Engine

on:
  schedule:
    # Monday nundi Friday varaku IST 09:10 AM (UTC 03:40 AM) ki start avtundi
    - cron: '40 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-live-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Intraday Continuous Engine
        run: |
          python main.py
