name: Aditya Trade Waves Daily Run

on:
  schedule:
    # Monday nundi Friday varaku Indian Standard Time (IST) 08:30 AM ki automatic ga run avtundi
    # UTC 03:00 AM ante IST 08:30 AM
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          pip install --upgrade pip
          pip install requests feedparser yfinance

      - name: Run Trading Script
        run: |
          python main.py
